### PR TITLE
Proposes call to action for projects page

### LINKED ISSUE #4: There should be a clear call to action on projects
As suggested by @ElenaFdR, we should say what people can do with or for a project on our projects page.

### PR DESCRIPTION
**Pull request by clausmullie**
Closes  #4

Or is this too much :sparkles: ? I thought it might be a nice way to get people's attention.

### CODE REVIEW

**Comment by ericherman** [comment]
> Or is this too much ✨ ? I thought it might be a nice way to get people's attention.

The sparkles are a bit too over-the-top for my tastes ... especially being on both sides.

Perhaps others feel differently.

**Comment by ElenaFdR** [comment]
I see where you're coming from, but I find the sparkles hard to spot when skimming down the page. Something brighter would work better. 
How many projects would we have them on at any point? I would suggest no more than, say, 3, to preserve the 'specialness' of the marker. NB: we're also currently seeking feedback on the procurement process code.

**Comment by Ainali** [comment]
I like the idea, but I think that the sparkles seem odd, as it usually highlights something that is good or new. And perhaps a single emoji at the start of the line is enough?

Perhaps a 💡 or 🛠️ would more symbolize that more work is needed here?

**Comment by clausmullie** [comment]
> NB: we're also currently seeking feedback on the procurement process code.

@ElenaFdR do you have a specific ask?

**Review by Ainali — DISMISSED** [review]

**Review by Ainali — APPROVED** [review]

**Comment by clausmullie** [comment]
For form I've taken out the introduction tweak from this PR

**Review by Ainali — APPROVED** [review]

**Pull request merged**
