### PR TITLE
fixing the markdown

### PR DESCRIPTION
**Pull request by PAPERPANKS**
image

Propose changes
------------------

**Smart Cities? Public Code!** is a collaboration ...

### CODE REVIEW

**Comment by bvhme** [comment]
Hey @PAPERPANKS, thanks for contributing, can you tell us a bit more about why you've made this Pull Request?

**Comment by PAPERPANKS** [comment]
I think there is a markdown mistake...
```<<Smart Cities? Public Code!>>```
and I have changed this into
```**Smart Cities? Public Code!**```

**Comment by PAPERPANKS** [comment]
**"Smart Cities? Public Code!"**

code :  `**"Smart Cities? Public Code!"**`

The above one looks good, lets use `"`

**Comment by bvhme** [comment]
I don't think we need the `**` emphasis, so let's lose that and then I'll merge :D

Thank you!

**Pull request closed without merging**
